# Generated by Django 5.1 on 2024-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('username', models.CharField(help_text='username must be unique and less than 36 characters', max_length=36, unique=True)),
                ('password', models.CharField(help_text='password must be less than 36 characters', max_length=36)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
