# Generated by Django 5.1 on 2024-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='password',
            field=models.CharField(help_text='password must be less than 36 characters', max_length=255),
        ),
    ]
