# Generated by Django 5.1 on 2024-08-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='cart must be unique and less than 10 characters', max_length=16, unique=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.costumer')),
                ('prodcuts', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
