# Generated by Django 5.1 on 2024-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.CharField(help_text='cart must be unique and less than 10 characters', max_length=16, unique=True),
        ),
    ]
