# Generated by Django 5.1 on 2024-08-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prodcuts',
            new_name='products',
        ),
    ]
